name: Luacheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: init.lua
